const data = {
    products: [
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/imahes/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Addidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 75,
            brand: 'Addidas',
            rating: 2.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/imahes/p3.jpg',
            price: 583,
            brand: 'Lacoste',
            rating: 3.5,
            numReviews: 18,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Nike Slim Pant',
            category: 'Pant',
            image: '/images/p4.jpg',
            price: 78,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 16,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Puma Slim Pant',
            category: 'Pant',
            image: '/images/p5.jpg',
            price: 194,
            brand: 'Puma',
            rating: 3.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Puma Slim Shirt',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 535,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'7',
            name: 'New balance Slim Shirt',
            category: 'Shirts',
            image: '/imahes/p6.jpg',
            price: 143,
            brand: 'New balance',
            rating: 4.0,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id:'8',
            name: 'Puma Fit Shirt',
            category: 'Shirts',
            image: '/images/p8.jpg',
            price: 134,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 40,
            description: 'high quality product',
        },
    ],
};
export default data;